[BUG] Valores negativos número de pedido
frmartellini/mm_stock pull request #22
Opened 2024-11-01 18:21 UTC by Danilo-Nunes

Why: Números negativos podem ser selecionados ou escritos por meio do teclado no campo Número do Pedido na tela de saída de produtos
How: Alterar as configurações do do input do mat form field para não permitir a inserção de números negativos por meio do selector e do teclado

2024-11-01 18:26 UTC, guiguat commented on front_end_ang/src/app/produto-saida/produto-saida.component.html
> +      <input type="number" id="NumPedidoInput" name="NumPedidoInput" formControlName="NumPedidoInput" (keypress)="permitirSomenteNumeros($event)"
precisa do keypress se ja tem o pattern?

2024-11-01 18:34 UTC, guiguat commented on front_end_ang/src/app/produto-saida/produto-saida.component.html
> +      <input type="number" id="NumPedidoInput" name="NumPedidoInput" formControlName="NumPedidoInput" (keypress)="permitirSomenteNumeros($event)"
talvez nem o pattern seja necessario se o step ta 1, eu tentaria por min=1, step=1 e ver como se comporta. mas sempre evitar keypress pq ele dispara a funcao toda vez q o cara tecla algo

2024-11-01 18:36 UTC, marcoslimabuhl requested changes

2024-11-01 18:36 UTC, marcoslimabuhl commented on front_end_ang/src/app/produto-saida/produto-saida.component.ts
> +
Qual a razão dessa função? Creio que só com a intervenção no html já resolva questão

2024-11-01 18:36 UTC, marcoslimabuhl commented on front_end_ang/src/app/produto-saida/produto-saida.component.html
> +      <input type="number" id="NumPedidoInput" name="NumPedidoInput" formControlName="NumPedidoInput" (keypress)="permitirSomenteNumeros($event)"
```suggestion
      <input type="number" id="NumPedidoInput" name="NumPedidoInput" formControlName="NumPedidoInput"
```

2024-11-01 18:36 UTC, marcoslimabuhl commented on front_end_ang/src/app/produto-saida/produto-saida.component.html
>               matInput [(ngModel)]="movimentacao.num_pedido"
```suggestion
             matInput min="1" step="1" pattern="^[0-9]+$" 
             [(ngModel)]="movimentacao.num_pedido"
```

2024-11-01 18:37 UTC, marcoslimabuhl requested changes

2024-11-01 18:37 UTC, marcoslimabuhl commented on front_end_ang/src/app/produto-saida/produto-saida.component.ts
> +  }
```suggestion
 ```

2024-11-01 18:47 UTC, marcoslimabuhl commented
![](https://github.trello.services/images/mini-trello-icon.png) [[BUG] Valores negativos número de pedido](https://trello.com/c/7wG2nhwn/57-bug-valores-negativos-n%C3%BAmero-de-pedido)

2024-11-01 19:50 UTC, Danilo-Nunes commented on front_end_ang/src/app/produto-saida/produto-saida.component.html
> +      <input type="number" id="NumPedidoInput" name="NumPedidoInput" formControlName="NumPedidoInput" (keypress)="permitirSomenteNumeros($event)"
ele impede do usuário burlar o selector com o teclado, por sanitizar as entradas do teclado

2024-11-03 00:06 UTC, merged

2025-03-31 00:08 UTC, guiguat commented
![](https://github.trello.services/images/mini-trello-icon.png) [Criar novo campo "Localização" no Cadastro de Produtos](https://trello.com/c/v7pTRLj9/63-criar-novo-campo-localiza%C3%A7%C3%A3o-no-cadastro-de-produtos)